In [87]:
#Assignment Question 1
import numpy as np
import math

In [ ]:
n = int(input('enter length: '))

enter length: 100


In [ ]:
Y = np.random.rand(n)
Y

array([0.4685677 , 0.70618012, 0.77012512, 0.77588449, 0.56418276,
       0.08252095, 0.00695775, 0.32526534, 0.16487874, 0.47378986,
       0.29175995, 0.81862984, 0.56277338, 0.95711376, 0.21281886,
       0.37807515, 0.92043155, 0.03914316, 0.49309345, 0.15408048,
       0.04561662, 0.5939891 , 0.24942857, 0.99413739, 0.54647912,
       0.17451759, 0.7609019 , 0.12869198, 0.64864495, 0.9407207 ,
       0.14687313, 0.22111537, 0.57001113, 0.62045327, 0.75894626,
       0.33765442, 0.11478816, 0.2389124 , 0.4916705 , 0.61745104,
       0.6330763 , 0.51462413, 0.0922649 , 0.52069235, 0.37497379,
       0.28853216, 0.72119842, 0.94989579, 0.80920435, 0.21447103,
       0.06482427, 0.79962249, 0.79544785, 0.47760858, 0.44765677,
       0.44076264, 0.96538126, 0.24148257, 0.80495409, 0.64128132,
       0.09428691, 0.89651583, 0.24455087, 0.5120907 , 0.20704435,
       0.19277823, 0.89124813, 0.27282381, 0.94054643, 0.77918847,
       0.02630712, 0.79041784, 0.49116459, 0.78944792, 0.47089

In [ ]:
Ycap = np.random.rand(n)
Ycap

array([0.83633285, 0.64954696, 0.5667874 , 0.91852709, 0.92521426,
       0.99824419, 0.78160814, 0.29237222, 0.08152658, 0.96750509,
       0.79030849, 0.12390617, 0.22216288, 0.31284618, 0.84734004,
       0.17300892, 0.90780689, 0.77465743, 0.00259266, 0.76086801,
       0.13133906, 0.82789531, 0.93286239, 0.4545544 , 0.4051433 ,
       0.20393603, 0.60537631, 0.22267656, 0.46859423, 0.47812924,
       0.0393038 , 0.00210076, 0.77730959, 0.86490745, 0.65884573,
       0.75333617, 0.19663   , 0.62768366, 0.09552048, 0.40090571,
       0.82340016, 0.71889249, 0.08596694, 0.30467154, 0.25824299,
       0.61230129, 0.64951064, 0.29259591, 0.1388414 , 0.99538102,
       0.25160219, 0.82294606, 0.28538576, 0.69985463, 0.43738686,
       0.54544125, 0.88097412, 0.77145375, 0.34670191, 0.22041882,
       0.22703894, 0.30177919, 0.45952388, 0.2018469 , 0.90383697,
       0.06617411, 0.3227167 , 0.70963053, 0.01135783, 0.41459667,
       0.09466103, 0.02440835, 0.45033301, 0.22643945, 0.09974

In [ ]:
Y[Y <= 0.5] = 0
Y[Y != 0] = 1    
    

In [ ]:
Y


array([0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.])

In [96]:

Ofunc = 0
for i in range(n):
  Onew = ((Y[i])*(math.log(2,Ycap[i]))+(1 - Y[i])*(math.log(2,(1 - Ycap[i]))))
  Ofunc += Onew

Ofunc = (-1/n)*Ofunc
print(Ofunc)

9.858048418627375


In [95]:
#Assignment Question 2
lst1 = [int(item) for item in input("Enter the list items : ").split()]
N  = int(input('target number: '))
outputd = dict()
total_combinations = len(lst1)*len(lst1)
t = 1
for i in range(len(lst1)):

  for j in range(len(lst1)):
    if (lst1[i] + lst1[j]) == N :
      outputd[t] = [i , j]
      t = t + 1 
    if t > total_combinations:
      break
print(outputd)
    




Enter the list items : 1 2 3
target number: 3
{1: [0, 1], 2: [1, 0]}
