In [21]:
#CROSS ENTROPY
import numpy as np
import math

In [15]:
n=int(input('Enter the value of n '))

Enter the value of n 5


In [16]:
y=np.random.randint(0,2,n)

In [17]:
y

array([0, 1, 1, 0, 1])

In [18]:
y_bar=np.random.rand(n)

In [19]:
y_bar

array([0.461046  , 0.44199888, 0.27622922, 0.72289472, 0.15312498])

In [20]:
sum=0
for i in range(n):
    sum=sum+y[i]*math.log2(y_bar[i])+ (1-y[i])*math.log2(1-y_bar[i])
O=sum/n*-1
print(O)

1.6968851660106616


In [22]:
#TARGET SUM
list1=[10,20,10,40,50,60,70]
n1=np.array(list1)

In [23]:
n1

array([10, 20, 10, 40, 50, 60, 70])

In [24]:
target=int(input("Enter the target sum "))

Enter the target sum 50


In [32]:
def target_sum(arr1, value):
    dict1={}
    m=1
    for i in range(len(arr1)):
        for j in range(len(arr1)):
            if arr1[i]+arr1[j]==value:
                dict1[m]=[i,j]
                m=m+1
    if m==1:
        print("Sorry no such cases exist")
        return 0
    else:
        return dict1


In [33]:
target_sum(n1,target)

{1: [0, 3], 2: [2, 3], 3: [3, 0], 4: [3, 2]}